version: '3.4'

services:
  api:
    image: keychain-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6000:5292"
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "9000:5432"
